### Inpatient Hospital Data Analysis ###

### Data Loading and Cleaning ###

In [2]:
import pandas as pd

# Loading file data
inpatient_data = pd.read_excel('Inpatient Data.xlsx')

# Displaying first 10 rows
inpatient_data.head(10)

,Patient_ID,Discarge_status,CareLevel,name,sex,age,ComorbidityCount,FamilySupport,InsurancePolicy_ID,HospitalBill,RoomNumber,AdmissionSource
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,725.00,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,7128.33,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,792.50,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,5310.00,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,805.00,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,845.83,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,5186.25,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,2107.50,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,1113.33,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,3007.08,NaN,C

In [3]:
# Dataset Shape
inpatient_data.shape
print("Shape of dataset: ", inpatient_data.shape)

Shape of dataset:  (891, 12)

In [4]:
# Dataset Info
inpatient_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient_ID          891 non-null    int64
 1   Discarge_status     891 non-null    int64
 2   CareLevel           891 non-null    int64
 3   name                891 non-null    object
 4   sex                 891 non-null    object
 5   age                 714 non-null    float64
 6   ComorbidityCount    891 non-null    int64
 7   FamilySupport       891 non-null    int64
 8   InsurancePolicy_ID  891 non-null    object
 9   HospitalBill        891 non-null    float64
 10  RoomNumber          204 non-null    object
 11  AdmissionSource     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
# Standardazing column name as per given meta data
inpatient_data.rename(columns={
    'Patient_ID': 'PatientID',
    'Discarge_status': 'DischargeStatus',
    'name': 'PatientName',
    'sex': 'Sex',
    'age': 'Age',
    'ComorbidityCount': 'ChronicConditionsCount',
    'FamilySupport': 'FamilySupportScore',
    'InsurancePolicy_ID': 'InsurancePolicyID' 
}, inplace=True)

# Verifying column name change
inpatient_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   PatientID               891 non-null    int64
 1   DischargeStatus         891 non-null    int64
 2   CareLevel               891 non-null    int64
 3   PatientName             891 non-null    object
 4   Sex                     891 non-null    object
 5   Age                     714 non-null    float64
 6   ChronicConditionsCount  891 non-null    int64
 7   FamilySupportScore      891 non-null    int64
 8   InsurancePolicyID       891 non-null    object
 9   HospitalBill            891 non-null    float64
 10  RoomNumber              204 non-null    object
 11  AdmissionSource         889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
is_missing = inpatient_data.isnull().values.any()
print("Is any values missing? ", is_missing)

Is any values missing?  True

In [7]:
# No. of missing values per column
missing_per_col = inpatient_data.isnull().sum()
print(missing_per_col)

PatientID                   0
DischargeStatus             0
CareLevel                   0
PatientName                 0
Sex                         0
Age                       177
ChronicConditionsCount      0
FamilySupportScore          0
InsurancePolicyID           0
HospitalBill                0
RoomNumber                687
AdmissionSource             2
dtype: int64

In [8]:
# Replacing missing age with median

# Create a copy for comparison
inpatient_data_original = inpatient_data.copy()

age_median = inpatient_data['Age'].median()
print("Median Age:", age_median)

# Replace age with Median
inpatient_data['Age'] = inpatient_data['Age'].fillna(age_median)

# Verify whether the age is replaced with Median
replaced_age = inpatient_data[inpatient_data_original['Age'].isnull()]
replaced_age.head(2)

Median Age: 28.0

,PatientID,DischargeStatus,CareLevel,PatientName,Sex,Age,ChronicConditionsCount,FamilySupportScore,InsurancePolicyID,HospitalBill,RoomNumber,AdmissionSource
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,845.83,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,28.0,0,0,244373,1300.00,NaN,S

In [10]:
# To drop rows where “AdmissionSource” is missing.
inpatient_data = inpatient_data.dropna(subset=['AdmissionSource'])

In [11]:
#Verification, after dropping rows
# No. of missing values per column
missing_per_col = inpatient_data.isnull().sum()
print(missing_per_col)

print("Shape after cleaning: " ,inpatient_data.shape)

PatientID                   0
DischargeStatus             0
CareLevel                   0
PatientName                 0
Sex                         0
Age                         0
ChronicConditionsCount      0
FamilySupportScore          0
InsurancePolicyID           0
HospitalBill                0
RoomNumber                687
AdmissionSource             0
dtype: int64
Shape after cleaning:  (889, 12)

In [12]:
# Convert age data type integer safely
inpatient_data['Age'] = inpatient_data['Age'].round().astype('Int64')

# Verify
print(inpatient_data['Age'].dtype)
inpatient_data.head(2)

Int64

,PatientID,DischargeStatus,CareLevel,PatientName,Sex,Age,ChronicConditionsCount,FamilySupportScore,InsurancePolicyID,HospitalBill,RoomNumber,AdmissionSource
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,725.00,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,7128.33,C85,C

### Statistical Analysis ###

In [13]:
# To calculate average age of patients

average_age = inpatient_data['Age'].mean().round().astype(int)
print("Average age of patients: ", average_age)

Average age of patients:  29

In [14]:
# Discharge status of each care level

# Grouping by CareLevel
carelevel_group = inpatient_data.groupby('CareLevel')

# Count Discharge Status
dischargestatus_count = carelevel_group['DischargeStatus'].value_counts(sort=False)

# Renaming Discharge Status values
dischargestatus_count = dischargestatus_count.rename(index={0: "Expired", 1: "Discharged alive"}, level='DischargeStatus')

print("Discharge Status grouped by Care Level:\n")
print(dischargestatus_count)

Discharge Status grouped by Care Level:

CareLevel  DischargeStatus
1          Expired              80
           Discharged alive    134
2          Expired              97
           Discharged alive     87
3          Expired             372
           Discharged alive    119
Name: count, dtype: int64

In [20]:
# Average hospital bill paid by survivors vs non-survivors

# Grouping by DischargeStatus
discharge_group = inpatient_data.groupby('DischargeStatus')

# Compute average HospitalBill per DischargeStatus
avg_bill_by_status = discharge_group['HospitalBill'].mean()

print("Average hospital bill paid by survivors vs non-survivors:\n")
print(round(avg_bill_by_status,2))

Average hospital bill paid by survivors vs non-survivors:

DischargeStatus
0    2211.79
1    4820.95
Name: HospitalBill, dtype: float64

In [30]:
# Correlation between hospital bill and patient age using NumPy

import numpy as np

# Extract numeric columns
age = inpatient_data['Age'].to_numpy()
bill = inpatient_data['HospitalBill'].to_numpy()

# Compute Pearson correlation
correlation = np.corrcoef(age, bill)[0, 1]

print("Correlation between Age and HospitalBill:", round(correlation,2))

print("Correlation Matrix:\n")
inpatient_data[['Age', 'HospitalBill']].corr()

Correlation between Age and HospitalBill: 0.09
Correlation Matrix:

                   Age  HospitalBill
Age           1.000000      0.093901
HospitalBill  0.093901      1.000000